on:
  push:
    branches:
    - main
  
jobs:
  deploy_on_vps:
    name: Déploiement sur le VPS
    runs-on: ubuntu-latest

    steps:
    - name: Déploiement sur le VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd ${VPS_PROJECT_LOCATION} && ./sync_with_main.sh
